/* Barrel de la géométrie pure (sans store). */
export { Projection } from "./Projection";
export type { WorldPoint, ScreenPoint } from "./Projection";
export { Box } from "./Box";
export type { BoxFace } from "./Box";
export { Painter } from "./Painter";
export type { LocalBox } from "./Painter";
export { RackGeometry } from "./RackGeometry";
export type { HalfExtents, WallGeo } from "./RackGeometry";
export { RackScene } from "./RackScene";
export type { OccupantInfo } from "./RackScene";
export { FreeEquipGeometry } from "./FreeEquipGeometry";
export type { FreeBox } from "./FreeEquipGeometry";
export { Resolver3D } from "./Resolver3D";
export type { Port3D } from "./Resolver3D";
export { GraphGeometry } from "./GraphGeometry";
export type { NodeSize, BBox } from "./GraphGeometry";
export { GridGeometry } from "./GridGeometry";
export { FloorLayout } from "./FloorLayout";
export type { MultiLayout, RoomPlacement, FloorPlane, BuildingBand, FloorCfg } from "./FloorLayout";
