import { Entity, Props } from "./Entity";
import { Normalize } from "../core/Normalize";
import { EQUIP_DEPTHS } from "../domain/constants";

/** Équipement : matériel répertorié, placé (rack / libre / sol / paroi) et câblé. */
export class Equipment extends Entity {
  name: string;
  type: string;
  brand: string;
  model: string;
  serial: string;
  purchase_date: string;
  po_ref: string;
  warranty_end: string;
  assigned_date: string;
  assigned_to: string;
  pdu_max_a: number | null;
  inventory_only: boolean;
  group_id: string | null;
  u_height: number;
  depth: string;
  depth_mm: number | null;
  locks_u: boolean;
  placement_mode: string;
  wall_lr: string;
  wall_margin: string;
  wall_u: number;
  wall_col: number;
  wall_orient: string;
  side_face: string;
  side_lr: string;
  side_u: number;
  side_col: number;
  side_snap: string;
  dim_mode: string;
  free_l_mm: number | null;
  free_w_mm: number | null;
  free_h_mm: number | null;
  dc_id: string | null;
  dc_x: number | null;
  dc_y: number | null;
  dc_z: number;
  dc_orientation: number;
  floor_x: number | null;
  floor_y: number | null;
  location: string;
  floor: string;
  room: string;
  rack_id: string | null;
  rack_u: number | null;
  rack_side: string;
  face_image_id: string | null;
  face_image_rear_id: string | null;
  face_image_top_id: string | null;
  face_image_bottom_id: string | null;
  face_image_left_id: string | null;
  face_image_right_id: string | null;
  face_image: string | null;
  face_image_rear: string | null;

  constructor(p: Props = {}) {
    super(p);
    this.name = p.name || "";
    this.type = p.type || "switch";
    this.brand = p.brand || "";
    this.model = p.model || "";
    this.serial = p.serial || "";
    this.purchase_date = p.purchase_date || "";
    this.po_ref = p.po_ref || "";
    this.warranty_end = p.warranty_end || "";
    this.assigned_date = p.assigned_date || "";
    this.assigned_to = p.assigned_to || "";
    this.pdu_max_a = (p.pdu_max_a != null && p.pdu_max_a !== "") ? Math.max(0, +p.pdu_max_a || 0) : null;
    this.inventory_only = p.inventory_only === true;
    this.group_id = p.group_id || null;
    this.u_height = (p.u_height != null) ? Math.max(1, p.u_height | 0)
      : (p.rack_u_height != null ? Math.max(1, p.rack_u_height | 0) : 1);
    this.depth = EQUIP_DEPTHS.includes(p.depth) ? p.depth
      : (p.rack_depth === "half" ? "half" : "full");
    this.depth_mm = (p.depth_mm != null && p.depth_mm !== "") ? Math.max(1, +p.depth_mm | 0) : null;
    this.locks_u = (this.depth === "full") ? true : (p.locks_u === true);
    this.placement_mode = (p.placement_mode === "rack") ? "rack" : (p.placement_mode === "side") ? "side" : (p.placement_mode === "wall") ? "wall" : (p.placement_mode === "floor") ? "floor" : "manual";
    this.wall_lr = (p.wall_lr === "right") ? "right" : "left";
    this.wall_margin = (p.wall_margin === "rear") ? "rear" : "front";
    this.wall_u = (p.wall_u != null) ? Math.max(1, p.wall_u | 0) : 1;
    this.wall_col = (p.wall_col != null) ? Math.max(0, p.wall_col | 0) : 0;
    this.wall_orient = (p.wall_orient === "facade") ? "facade" : "center";
    this.side_face = (p.side_face === "rear") ? "rear" : "front";
    this.side_lr = (p.side_lr === "right") ? "right" : "left";
    this.side_u = (p.side_u != null) ? Math.max(1, p.side_u | 0) : 1;
    this.side_col = (p.side_col === 1 || p.side_col === "1") ? 1 : 0;
    this.side_snap = (p.side_snap === "wall") ? "wall" : "post";
    this.dim_mode = (p.dim_mode === "free" || p.dim_mode === "u") ? p.dim_mode
      : (this.placement_mode === "rack" ? "u" : "free");
    this.free_l_mm = (p.free_l_mm != null) ? Math.max(0, Math.round(+p.free_l_mm) || 0) : null;
    this.free_w_mm = (p.free_w_mm != null) ? Math.max(0, Math.round(+p.free_w_mm) || 0) : null;
    this.free_h_mm = (p.free_h_mm != null) ? Math.max(0, Math.round(+p.free_h_mm) || 0) : null;
    this.dc_id = p.dc_id || null;
    this.dc_x = (p.dc_x != null) ? +p.dc_x : null;
    this.dc_y = (p.dc_y != null) ? +p.dc_y : null;
    this.dc_z = (p.dc_z != null) ? (Math.round(+p.dc_z) || 0) : 0;
    this.dc_orientation = Normalize.rackOrientation(p.dc_orientation);
    this.floor_x = (p.floor_x != null) ? +p.floor_x : null;
    this.floor_y = (p.floor_y != null) ? +p.floor_y : null;
    this.location = p.location || "";
    this.floor = p.floor || "";
    this.room = p.room || "";
    this.rack_id = p.rack_id || null;
    this.rack_u = (p.rack_u != null) ? (p.rack_u | 0) : null;
    this.rack_side = (p.rack_side === "rear") ? "rear" : "front";
    this.face_image_id = p.face_image_id || null;
    this.face_image_rear_id = p.face_image_rear_id || null;
    this.face_image_top_id = p.face_image_top_id || null;
    this.face_image_bottom_id = p.face_image_bottom_id || null;
    this.face_image_left_id = p.face_image_left_id || null;
    this.face_image_right_id = p.face_image_right_id || null;
    this.face_image = p.face_image || null;
    this.face_image_rear = p.face_image_rear || null;
  }
}
